#!/usr/bin/env bash
#
# mayhem/build.sh — build libcacard's 7816 APDU-parser fuzz harness + the
# behavioral-oracle probe.
#
# Fuzz target:
#   fuzz_apdu — in-process libFuzzer harness over src/card_7816.c's
#               vcard_apdu_new() (the 7816-4 APDU parser: class/channel/secure-
#               messaging decode + Lc/Le short & extended length decoding). This
#               is the code every byte an untrusted card-reader sends hits first.
#               Byte-in, no file I/O, no NSS/emulator init at runtime.
#
# We compile the WHOLE libcacard library (src/*.c minus the vscclient client
# binary and the PC/SC-only capcsc.c), exactly like upstream's own fuzz build
# (objects: libcacard.extract_all_objects()), so vcard_apdu_new's translation
# unit (card_7816.c) links its cross-module references cleanly. NSS is a
# compile/link dependency of the emulator sources; vcard_apdu_new itself needs
# no runtime NSS init, so the harness stays pure byte-in.
#
# The PROJECT code is compiled with $SANITIZER_FLAGS AND -fsanitize=fuzzer-no-link
# UNCONDITIONALLY so the fuzzed code carries SanCov instrumentation (otherwise
# 0 edges in Mayhem), plus $DEBUG_FLAGS for DWARF<4 (the base's SANITIZER_FLAGS
# ends in a plain -g = DWARF5, so -gdwarf-3 must come AFTER it).
#
# Every ASan-built binary (fuzz_apdu, fuzz_apdu-standalone) also links
# mayhem/lsan_off.cc — the build-time __lsan_is_turned_off() hook that disables
# ONLY leak detection (fleet policy; ASan + UBSan stay on and halting).
#
# The oracle probe is a SEPARATE clean build with NORMAL flags (no sanitizer,
# no -gdwarf-3), dynamically linked so mayhem/test.sh's LD_PRELOAD sabotage
# check bites.
set -euo pipefail

[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer}"
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
: "${CC:=clang}"
: "${CXX:=clang++}"
: "${LIB_FUZZING_ENGINE:=-fsanitize=fuzzer}"
: "${STANDALONE_FUZZ_MAIN:=/opt/mayhem/StandaloneFuzzTargetMain.c}"

SRC="${SRC:-/mayhem}"
cd "$SRC"

# Split flag strings into arrays so multi-word env values word-split correctly.
read -r -a SAN_ARR   <<< "$SANITIZER_FLAGS"
read -r -a DBG_ARR   <<< "$DEBUG_FLAGS"
read -r -a FUZZ_ARR  <<< "$LIB_FUZZING_ENGINE"
read -r -a GLIB_CF   <<< "$(pkg-config --cflags glib-2.0)"
read -r -a GLIB_LD   <<< "$(pkg-config --libs   glib-2.0)"
read -r -a NSS_CF    <<< "$(pkg-config --cflags nss)"
read -r -a NSS_LD    <<< "$(pkg-config --libs   nss)"

HDIR="$SRC/mayhem/harnesses"
PDIR="$SRC/mayhem/probes"
BUILD="$SRC/mayhem-build"
mkdir -p "$BUILD"

# config.h is normally generated by meson/autotools; the only knob is ENABLE_PCSC
# (PC/SC is not installed in the commit image), so a one-line header suffices.
{ echo "/* generated by mayhem/build.sh */"; echo "#undef ENABLE_PCSC"; } > "$BUILD/config.h"

# Common include roots: $BUILD (config.h), repo root, and src/.
INC=(-I"$BUILD" -I"$SRC" -I"$SRC/src" "${GLIB_CF[@]}" "${NSS_CF[@]}" '-DG_LOG_DOMAIN="libcacard"' -std=gnu99)

# The library sources (upstream libcacard_src, minus capcsc.c = PC/SC-only and
# vscclient.c = owns main()).
LIB_SRCS=(
  src/cac-aca.c src/cac.c src/card_7816.c src/common.c src/event.c
  src/gp.c src/msft.c src/simpletlv.c src/vcard.c src/vcard_emul_nss.c
  src/vcard_emul_type.c src/vcardt.c src/vreader.c
)

echo "== build.sh: SANITIZER_FLAGS=[$SANITIZER_FLAGS] DEBUG_FLAGS=[$DEBUG_FLAGS] =="

# ---------------------------------------------------------------------------
# Standalone run-once driver (a C file) — compiled ONCE, linked per harness.
# ---------------------------------------------------------------------------
"$CC" "${SAN_ARR[@]}" "${DBG_ARR[@]}" -x c -c "$STANDALONE_FUZZ_MAIN" \
    -o "$BUILD/standalone_main.o"

# ---------------------------------------------------------------------------
# Build-time LSan off-switch (mayhem/lsan_off.cc) — compiled ONCE with the same
# sanitizer/debug flags, linked into every ASan-built binary below.
# ---------------------------------------------------------------------------
"$CXX" "${SAN_ARR[@]}" "${DBG_ARR[@]}" -c "$SRC/mayhem/lsan_off.cc" \
    -o "$BUILD/lsan_off.o"

# ---------------------------------------------------------------------------
# Target: fuzz_apdu — instrument every library source (sanitizer + fuzzer-no-link
# ALWAYS) so the whole parser carries SanCov edges.
# ---------------------------------------------------------------------------
SAN_OBJS=()
for f in "${LIB_SRCS[@]}"; do
  o="$BUILD/$(echo "$f" | tr '/.' '__').san.o"
  "$CC" "${SAN_ARR[@]}" "${DBG_ARR[@]}" -fsanitize=fuzzer-no-link \
      "${INC[@]}" -c "$SRC/$f" -o "$o"
  SAN_OBJS+=("$o")
done

"$CC" "${SAN_ARR[@]}" "${DBG_ARR[@]}" -fsanitize=fuzzer-no-link \
    "${INC[@]}" -c "$HDIR/fuzz_apdu.c" -o "$BUILD/fuzz_apdu.o"

"$CC" "${SAN_ARR[@]}" "${DBG_ARR[@]}" "${FUZZ_ARR[@]}" \
    "$BUILD/fuzz_apdu.o" "$BUILD/lsan_off.o" "${SAN_OBJS[@]}" \
    "${GLIB_LD[@]}" "${NSS_LD[@]}" \
    -o /mayhem/fuzz_apdu

"$CC" "${SAN_ARR[@]}" "${DBG_ARR[@]}" \
    "$BUILD/standalone_main.o" "$BUILD/fuzz_apdu.o" "$BUILD/lsan_off.o" \
    "${SAN_OBJS[@]}" "${GLIB_LD[@]}" "${NSS_LD[@]}" \
    -o /mayhem/fuzz_apdu-standalone

# ---------------------------------------------------------------------------
# Oracle probe — CLEAN build (NORMAL flags; NO sanitizer, NO -gdwarf-3),
# dynamically linked so mayhem/test.sh's LD_PRELOAD sabotage shim can reach it.
# ---------------------------------------------------------------------------
CLEAN_SRCS=()
for f in "${LIB_SRCS[@]}"; do CLEAN_SRCS+=("$SRC/$f"); done
"$CC" -O2 "${INC[@]}" "$PDIR/apdu_probe.c" "${CLEAN_SRCS[@]}" \
    "${GLIB_LD[@]}" "${NSS_LD[@]}" -o /mayhem/apdu_probe

if ! file /mayhem/apdu_probe | grep -q 'dynamically linked'; then
    echo "FATAL: /mayhem/apdu_probe is not dynamically linked — oracle would be un-neuterable" >&2
    file /mayhem/apdu_probe >&2
    exit 1
fi

echo "== build.sh: OK =="
ls -l /mayhem/fuzz_apdu /mayhem/fuzz_apdu-standalone /mayhem/apdu_probe
